# Generated by Django 4.2.8 on 2024-05-13 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('desc', models.TextField()),
                ('actors', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='gallery')),
                ('date', models.DateField()),
                ('youtube_trailer', models.URLField(max_length=250)),
                ('genres', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moviewebsiteapp.genres')),
            ],
            options={
                'verbose_name': 'movie',
                'verbose_name_plural': 'movies',
                'ordering': ('name',),
            },
        ),
    ]
