# Generated by Django 4.2.8 on 2024-05-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviewebsiteapp', '0002_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
